Update sending-moments-events.md
SteelSeries/gamesense-sdk pull request #103
Opened 2020-11-17 23:58 UTC by elliequirini

add documentation for autoclipping api

2020-11-18 13:43 UTC, ToadKing requested changes

2020-11-18 13:43 UTC, ToadKing commented on doc/api/sending-moments-events.md
> +`default_enabled`: <int> (0-1)    enabled by default    optional - default `0`
This should be a boolean instead of an integer flag if the only values are 0 and 1.

2020-12-03 22:11 UTC, ToadKing approved these changes

2020-12-03 22:37 UTC, elliequirini commented
add documentation for autoclipping api

2020-12-03 22:37 UTC, merged